### ISSUE TITLE
Tiến độ 19-03-04

### ISSUE THREAD

**Issue by TriDang** [TriDang/house-designer#3]
-@tranminhthien1304  và @thinhct95 cập nhật tình hình LVTN cho thầy
-Ngoài code ra, nhớ cập nhật LVTN. Thời gian đầu nhóm có cập nhật, nhưng đến giờ đã lâu mà vẫn chưa thấy thay đổi gì

**Comment by TriDang** [comment]
@tranminhthien1304  @thinhct95 
-Các features nào đã hiện thực/chưa hiện thực sao không thấy 2 đứa update cho thầy vậy?

**Comment by thinhct95** [comment]
@TriDang Dạ, bọn em xin lỗi thầy, từ bây giờ bọn em sẽ để ý phần issues này hơn ạ. Em mới gửi 1 email tóm tắt cho thầy. Không biết khi nào tuần sau thầy có thời gian để bọn em có thể gặp thầy để báo cáo tiến độ được không ạ. @tranminhthien1304

**Comment by thinhct95** [comment]
@TriDang Lịch học của em là tối t3, t5, t6 đến 20h30 phút ạ. T7 và chủ nhật thì em học đến 18h
